### ISSUE TITLE
Support merging datastores from different preston instances

### ISSUE THREAD

**Issue by mjcollin** [bio-guoda/preston#8]
The data that preston collects goes in to a folder by hash. This data is safe to rsync and merge together from multiple sources.

However, the hexastore data that is the results of queries is not. An example query would be "what is the first copy of dataset X" who's hash would be the same on any server. But the answer to that is different on each server. Since the question hash is the same, rsyncing would have only one server win instead of the true answer which involves reanalyzing the resulting merged data store.

**Comment by jhpoelen** [comment]
Example of a preston dataset graph crawl history
```console
$ preston history 
<0659a54f-b713-4f86-a917-5be166a14110> <http://purl.org/pav/hasVersion> <hash://sha256/c253a5311a20c2fc082bf9bac87a1ec5eb6e4e51ff936e7be20c29c8e77dee55> . <hash://sha256/b83cf099449dae3f633af618b19d05013953e7a1d7d97bc5ac01afd7bd9abe5d> <http://www.w3.org/ns/prov#generatedAtTime> "2018-09-04T20:48:35.096Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> . <hash://sha256/b83cf099449dae3f633af618b19d05013953e7a1d7d97bc5ac01afd7bd9abe5d> <http://purl.org/pav/previousVersion> <hash://sha256/c253a5311a20c2fc082bf9bac87a1ec5eb6e4e51ff936e7be20c29c8e77dee55> . 
...
<hash://sha256/e4e5736e8bfec6c686eedde4c6dfa62845930d04e12dfa6f8a7d70abc3d087df> <http://www.w3.org/ns/prov#generatedAtTime> "2018-11-07T18:35:07.399Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> . <hash://sha256/e4e5736e8bfec6c686eedde4c6dfa62845930d04e12dfa6f8a7d70abc3d087df> <http://purl.org/pav/previousVersion> <hash://sha256/650a28fff3e03dadba70dc05a34c580c04203380187953fa4a2fb778353fee79> .
```

**Comment by jhpoelen** [comment]
One way to deal with the merging of multiple repositories is to use multiple preston remotes :

Example ```preston history --remotes https://example.org/prov/,https://deeplinker.bio```, would first attempt to find a Preston provenance history at https://example.org/prov/ , then try https://deeplinker.bio. This construction allows for the first remote (e.g., https://example.org/prov/) to serve lightweight provenance history (see https://github.com/bio-guoda/preston/blob/master/architecture.md#simplified-hexastore) and the second (e.g., https://deeplinker.bio), or subsequent) to serve provenance records and/or tracked content.

So, the cascading remotes allow for composition of provenance history, provenance and data records across different remotes.

**Comment by jhpoelen** [comment]
However, this still leaves the integration of the data in a single data dir. More work is needed to avoid merge conflicts there.

**Comment by jhpoelen** [comment]
Now, you can merge preston archive with one or more other ones using:

```
$ preston merge [content id1] [content id2] . . .  
```

where content ids are the provenance hashes or snapshots of the specific preston archive to merge with. 

so, I'd you'd like to merge a >1 TB preston archive (including over three years worth of biodiversity data archive snapshots) into your preston archive using statements like:

```
preston merge hash://sha256/b771ed09aea78055e39d5c955997e5d9b42dd9edc6b094d9b8a27df16bdc6b6c
...
<hash://sha256/c6f8e1a37e87e4542748cdddd2465956236fb290672e4bef04964a4f12989237> <http://www.w3.org/ns/prov#usedBy> <urn:uuid:48b2e8a4-0d53-4ea8-84c9-b86ed2e0eadc> <urn:uuid:48b2e8a4-0d53-4ea8-84c9-b86ed2e0eadc> .
<hash://sha256/b771ed09aea78055e39d5c955997e5d9b42dd9edc6b094d9b8a27df16bdc6b6c> <http://www.w3.org/ns/prov#usedBy> <urn:uuid:48b2e8a4-0d53-4ea8-84c9-b86ed2e0eadc> <urn:uuid:48b2e8a4-0d53-4ea8-84c9-b86ed2e0eadc> .
```

This command appends the newly created dependency on, or use of, the  Preston archive defined by hash://sha256/b771ed09aea78055e39d5c955997e5d9b42dd9edc6b094d9b8a27df16bdc6b6c , with another preston archive defined by hash://sha256/c6f8e1a37e87e4542748cdddd2465956236fb290672e4bef04964a4f12989237

**Comment by jhpoelen** [comment]
@mjcollin apologies for the long wait for the merge feature. I hope the wait was worth it ; )

@mielliott please review.

**Comment by jhpoelen** [comment]
Note that the associated content can be pulled in using the customary combination of ```preston cat```, ```preston history```, ```preston ls``` etc. 

A new command, ```preston origins``` is in the works to help traverse the entire dependency tree, or all the origins of a specific dataset.

**Comment by jhpoelen** [comment]
@mielliott thanks for sharing your notes! Yes, the ```preston origins``` commands needs a little tlc. I think the root cause is that Preston gets a bit forgetful when retrieving remote provenance logs and . . . hasn't quite figured out recursion into merged provenance logs yet. Hoping to reproduce in test cases and have a look. Don't want to distract you from writing the paper, but please do holler if you need a distraction ; )

**Comment by jhpoelen** [comment]
Just did some refactoring and implemented some unit tests to reproduce the issue . See https://github.com/bio-guoda/preston/blob/93a8f9712eb644b0c83e16037c0cf6ceb9d4f7da/preston-get/src/test/java/bio/guoda/preston/store/TracerOfOriginsTest.java#L170 . 

Reproducing is the hard part . . . now only fixing it ; )

**Comment by jhpoelen** [comment]
After updating the code, now:

```
$ mkdir obs1
$ cd obs1/
$ preston track https://google.com
$ preston track https://google.com
$ preston history
<urn:uuid:0659a54f-b713-4f86-a917-5be166a14110> <http://purl.org/pav/hasVersion> <hash://sha256/a0d5db1ab02c2d477b162ff789aa892ed1c7d38bc83d303a522c11ff2174e919> .
<hash://sha256/dee7c669fe03dc1a10b7424fa604e27aaac7424725d4f8eb7d6a3d3e51709181> <http://purl.org/pav/previousVersion> <hash://sha256/a0d5db1ab02c2d477b162ff789aa892ed1c7d38bc83d303a522c11ff2174e919> .
```

and 

```
$ mkdir obs2
$ cd obs2
$ preston track https://duckduckgo.com
$ preston track https://duckduckgo.com
<urn:uuid:0659a54f-b713-4f86-a917-5be166a14110> <http://purl.org/pav/hasVersion> <hash://sha256/6ca3873f499c2a9b5dfb6b35195cc956a3e6f6954421211892def068485fc0d8> .
<hash://sha256/e4994f5aaa4104e017c514221d2200ad8ac0d4178f92a11d245a83e154fe56f3> <http://purl.org/pav/previousVersion> <hash://sha256/6ca3873f499c2a9b5dfb6b35195cc956a3e6f6954421211892def068485fc0d8> .
```

Now merge obs1 into obs2 using

```
$ preston merge hash://sha256/dee7c669fe03dc1a10b7424fa604e27aaac7424725d4f8eb7d6a3d3e51709181
[...]
```

Then, trace origins using

```
$ preston origins --remote file:///$PWD/../obs1/data
$ preston origins --remote file://$PWD/../obs1/data hash://sha256/af1a9a11b85d152349d280717a420f12c2a4d9f3724c058f64db973d196fdea1
<hash://sha256/af1a9a11b85d152349d280717a420f12c2a4d9f3724c058f64db973d196fdea1> <http://www.w3.org/ns/prov#wasDerivedFrom> <hash://sha256/e4994f5aaa4104e017c514221d2200ad8ac0d4178f92a11d245a83e154fe56f3> .
<hash://sha256/af1a9a11b85d152349d280717a420f12c2a4d9f3724c058f64db973d196fdea1> <http://www.w3.org/ns/prov#wasDerivedFrom> <hash://sha256/dee7c669fe03dc1a10b7424fa604e27aaac7424725d4f8eb7d6a3d3e51709181> .
<hash://sha256/e4994f5aaa4104e017c514221d2200ad8ac0d4178f92a11d245a83e154fe56f3> <http://www.w3.org/ns/prov#wasDerivedFrom> <hash://sha256/6ca3873f499c2a9b5dfb6b35195cc956a3e6f6954421211892def068485fc0d8> .
[file:///home/jorrit/tmp/...5d4f8eb7d6a3d3e51709181] 100.0% of 3 kB at 0.42 MB/s completed in < 1 minute
<hash://sha256/dee7c669fe03dc1a10b7424fa604e27aaac7424725d4f8eb7d6a3d3e51709181> <http://www.w3.org/ns/prov#wasDerivedFrom> <hash://sha256/a0d5db1ab02c2d477b162ff789aa892ed1c7d38bc83d303a522c11ff2174e919> .
<urn:uuid:0659a54f-b713-4f86-a917-5be166a14110> <http://purl.org/pav/hasVersion> <hash://sha256/6ca3873f499c2a9b5dfb6b35195cc956a3e6f6954421211892def068485fc0d8> .
[file:///home/jorrit/tmp/...83d303a522c11ff2174e919] 100.0% of 3 kB at 1.78 MB/s completed in < 1 minute
<urn:uuid:0659a54f-b713-4f86-a917-5be166a14110> <http://purl.org/pav/hasVersion> <hash://sha256/a0d5db1ab02c2d477b162ff789aa892ed1c7d38bc83d303a522c11ff2174e919> .
```

Now, running it again, without a remote ... same results, so results are cached. 

```
$ preston origins hash://sha256/af1a9a11b85d152349d280717a420f12c2a4d9f3724c058f64db973d196fdea1
<hash://sha256/af1a9a11b85d152349d280717a420f12c2a4d9f3724c058f64db973d196fdea1> <http://www.w3.org/ns/prov#wasDerivedFrom> <hash://sha256/e4994f5aaa4104e017c514221d2200ad8ac0d4178f92a11d245a83e154fe56f3> .
<hash://sha256/af1a9a11b85d152349d280717a420f12c2a4d9f3724c058f64db973d196fdea1> <http://www.w3.org/ns/prov#wasDerivedFrom> <hash://sha256/dee7c669fe03dc1a10b7424fa604e27aaac7424725d4f8eb7d6a3d3e51709181> .
<hash://sha256/e4994f5aaa4104e017c514221d2200ad8ac0d4178f92a11d245a83e154fe56f3> <http://www.w3.org/ns/prov#wasDerivedFrom> <hash://sha256/6ca3873f499c2a9b5dfb6b35195cc956a3e6f6954421211892def068485fc0d8> .
<hash://sha256/dee7c669fe03dc1a10b7424fa604e27aaac7424725d4f8eb7d6a3d3e51709181> <http://www.w3.org/ns/prov#wasDerivedFrom> <hash://sha256/a0d5db1ab02c2d477b162ff789aa892ed1c7d38bc83d303a522c11ff2174e919> .
<urn:uuid:0659a54f-b713-4f86-a917-5be166a14110> <http://purl.org/pav/hasVersion> <hash://sha256/6ca3873f499c2a9b5dfb6b35195cc956a3e6f6954421211892def068485fc0d8> .
<urn:uuid:0659a54f-b713-4f86-a917-5be166a14110> <http://purl.org/pav/hasVersion> <hash://sha256/a0d5db1ab02c2d477b162ff789aa892ed1c7d38bc83d303a522c11ff2174e919> .
```

In ASCII art

```

(af1a) - [:wasDerivedFrom] -> (e499) - [:wasDerivedFrom] -> (6ca3) <- [:wasDerivedFrom] -\ 
     \ - [:wasDerivedFrom] -> (dee7) - [:wasDerivedFrom] -> (a0d5) <- [:wasDerivedFrom] - (urn:uuid:0659 aka big bang)
     
```

@mielliott please confirm that the behavior is now as expected.

**Comment by mielliott** [comment]
Thanks for fixing and recreating my tests! Although I'm having some issues tracking stuff now...

```
$ preston version
0.0.1-SNAPSHOT

$ preston track https://duckduckgo.com
[main] ERROR bio.guoda.preston.cmd.CmdLine - unexpected exception
java.lang.NoSuchMethodError: bio.guoda.preston.process.ProcessorReadOnly.<init>(Lbio/guoda/preston/store/BlobStoreReadOnly;[Lbio/guoda/preston/process/StatementsListener;)V
        at bio.guoda.preston.process.RegistryReaderIDigBio.<init>(RegistryReaderIDigBio.java:71)
        at bio.guoda.preston.process.RegistryReaderIDigBio.<init>(RegistryReaderIDigBio.java:67)
        at bio.guoda.preston.cmd.CmdActivity.createProcessors(CmdActivity.java:177)
        at bio.guoda.preston.cmd.CmdActivity.createStatementListeners(CmdActivity.java:147)
        at bio.guoda.preston.cmd.CmdActivity.initListeners(CmdActivity.java:135)
        at bio.guoda.preston.cmd.CmdActivity.run(CmdActivity.java:119)
        at bio.guoda.preston.cmd.CmdActivity.run(CmdActivity.java:86)
        at bio.guoda.preston.cmd.CmdLine.run(CmdLine.java:18)
        at bio.guoda.preston.cmd.CmdLine.run(CmdLine.java:26)
        at bio.guoda.preston.Preston.main(Preston.java:14)
java.lang.NoSuchMethodError: bio.guoda.preston.process.ProcessorReadOnly.<init>(Lbio/guoda/preston/store/BlobStoreReadOnly;[Lbio/guoda/preston/process/StatementsListener;)V
        at bio.guoda.preston.process.RegistryReaderIDigBio.<init>(RegistryReaderIDigBio.java:71)
        at bio.guoda.preston.process.RegistryReaderIDigBio.<init>(RegistryReaderIDigBio.java:67)
        at bio.guoda.preston.cmd.CmdActivity.createProcessors(CmdActivity.java:177)
        at bio.guoda.preston.cmd.CmdActivity.createStatementListeners(CmdActivity.java:147)
        at bio.guoda.preston.cmd.CmdActivity.initListeners(CmdActivity.java:135)
        at bio.guoda.preston.cmd.CmdActivity.run(CmdActivity.java:119)
        at bio.guoda.preston.cmd.CmdActivity.run(CmdActivity.java:86)
        at bio.guoda.preston.cmd.CmdLine.run(CmdLine.java:18)
        at bio.guoda.preston.cmd.CmdLine.run(CmdLine.java:26)
        at bio.guoda.preston.Preston.main(Preston.java:14)
```

I don't think it's an issue with my computer, it works fine with preston 0.3.5.

**Comment by jhpoelen** [comment]
Hmm. did you do ```mvn clean package```  to rebuild?

**Comment by mielliott** [comment]
Ahhhh that fixed it, thanks! All is well now. Case closed?

**Comment by jhpoelen** [comment]
Oef! I was hoping it was some stale class file hanging out somewhere. Please feel free to close the issue if you the feature behaves as expected. 

Now . . . we'll have to write the manuscript "On The Origins Of Data" . Can you feel it?
